### ISSUE TITLE
Using private CA (certificate authority)

### ISSUE THREAD

**Issue by c-git** [rerun-io/ewebsock#56]
For public facing sites the `rustls-tls-webpki-roots` on `tungstenite` that is enabled when the `tls` [feature](https://github.com/rerun-io/ewebsock/blob/636d3912e1d2e7389f343774a1ad8f8ec77df085/ewebsock/Cargo.toml#L26C1-L26C46) is enabled is fine. However, I was working on an internal service and we have our own private CA. That feature does not work as even though I have the rootCA.crt installed on my OS (Ubuntu) the service certificate still was not able to be validated. I finally got it to work by adding 

```toml
# Cargo.toml
[dependencies]
tungstenite = { version = "*", default-features = false, features = ["rustls-tls-native-roots"] }
```

to my `Cargo.toml`. Others can also work around it this way but maybe a feature on `ewebsock` to enable it might make sense.
